@URL = http://127.0.0.1:8000/api
@token = 5|BlB3rzc62fJNM6SzrrXy7j3oHTthmxNVLMNZuNja6cc89bf9

### Register User
POST {{URL}}/register
Content-Type: application/json
Accept: : application/json

{
    "name" : "Aditya Wijayanto",
    "email" : "aditya@example.com",
    "password" : "password123",
    "password_confirmation" : "password123"
}

### Verify Email
GET {{URL}}/email/verify/1/761d6b19208dc55ce8caf89e3341fb30ea529d09?expires=1773005930&signature=6836492a55280ccbf029442fecb3909dfc21fdadecc3f828a3f824accb607ccd
Accept: application/json

### Login User
POST {{URL}}/login
Content-Type: application/json
Accept: application/json

{
    "email" : "aditya@example.com",
    "password" : "password123"
}

### Get User Profile
GET {{URL}}/user
Accept: application/json
Authorization: Bearer {{token}}

### Update Profile
PATCH {{URL}}/updateProfile
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

 {
    "name" : "Aditya Wijayanto"
 }

### Logout User
POST {{URL}}/logout
Accept: application/json
Authorization: Bearer {{token}}

### Change Password
PATCH {{URL}}/changePassword
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "old_password" : "password123",
    "new_password" : "123123123",
    "new_password_confirmation" : "123123123"
}
